[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.js
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | env
  | venv
)/
'''
