# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    paths-ignore:
      - '**.md'
      - docs/**
    branches:
      - 'develop'
      - 'master'
    tags:
      - '*'

  pull_request:
    paths-ignore:
      - '**.md'
      - docs/**
    branches:
      - 'develop'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [1.11, 2.2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django~=${{ matrix.django-version }}.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics

    - name: Run tests with pytest
      run: pytest --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: ${{ matrix.python-version == '3.9' && matrix.django-version == '2.2' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false

